// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSd_55XiG3ub_dM2lUkfFVz0IhK_gmyL4',
    appId: '1:362368539743:web:2926d03940fd18c8af4fea',
    messagingSenderId: '362368539743',
    projectId: 'pokemon-api-31315',
    authDomain: 'pokemon-api-31315.firebaseapp.com',
    storageBucket: 'pokemon-api-31315.appspot.com',
    measurementId: 'G-TDMLRDWQFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLjf09f5U1bBjFNHSZ5KZiuQ_LKYzCbE',
    appId: '1:362368539743:android:664bc141f2703ed1af4fea',
    messagingSenderId: '362368539743',
    projectId: 'pokemon-api-31315',
    storageBucket: 'pokemon-api-31315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfEZoE994rrLGjUOiB5Ewlu7wT5FCp02E',
    appId: '1:362368539743:ios:7cea16bf87782bd4af4fea',
    messagingSenderId: '362368539743',
    projectId: 'pokemon-api-31315',
    storageBucket: 'pokemon-api-31315.appspot.com',
    iosClientId: '362368539743-1pnh2j7gjoj3dffrlj3nq31rlbnucpv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkmnApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfEZoE994rrLGjUOiB5Ewlu7wT5FCp02E',
    appId: '1:362368539743:ios:6e09bb016a856504af4fea',
    messagingSenderId: '362368539743',
    projectId: 'pokemon-api-31315',
    storageBucket: 'pokemon-api-31315.appspot.com',
    iosClientId: '362368539743-9kdh5pnmooc7qobg54b8r6rle5t3hoac.apps.googleusercontent.com',
    iosBundleId: 'com.example.pkmnApi.RunnerTests',
  );
}
